# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 691)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableView = QtWidgets.QTableView(parent=self.splitter)
        self.tableView.setObjectName("tableView")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.splitter)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 19))
        self.menubar.setObjectName("menubar")
        self.menuActions = QtWidgets.QMenu(parent=self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSearch_for_repositories = QtGui.QAction(parent=MainWindow)
        self.actionSearch_for_repositories.setObjectName("actionSearch_for_repositories")
        self.actionRefresh_all = QtGui.QAction(parent=MainWindow)
        self.actionRefresh_all.setObjectName("actionRefresh_all")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionVisit_GitHub = QtGui.QAction(parent=MainWindow)
        self.actionVisit_GitHub.setObjectName("actionVisit_GitHub")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuActions.addAction(self.actionRefresh_all)
        self.menuActions.addAction(self.actionSearch_for_repositories)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionVisit_GitHub)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuActions.setTitle(_translate("MainWindow", "&Actions"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.actionSearch_for_repositories.setText(_translate("MainWindow", "&Search for repositories..."))
        self.actionRefresh_all.setText(_translate("MainWindow", "&Refresh all"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionSettings.setText(_translate("MainWindow", "&Settings..."))
        self.actionVisit_GitHub.setText(_translate("MainWindow", "View on &GitHub ↗"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
