# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(556, 221)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_terminal = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_terminal.setObjectName("lineEdit_terminal")
        self.gridLayout.addWidget(self.lineEdit_terminal, 2, 1, 1, 1)
        self.checkBox_fetches = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_fetches.setText("")
        self.checkBox_fetches.setObjectName("checkBox_fetches")
        self.gridLayout.addWidget(self.checkBox_fetches, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lineEdit_IDE = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_IDE.setObjectName("lineEdit_IDE")
        self.gridLayout.addWidget(self.lineEdit_IDE, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_settings_location = QtWidgets.QLabel(parent=Dialog)
        self.label_settings_location.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_settings_location.setObjectName("label_settings_location")
        self.gridLayout.addWidget(self.label_settings_location, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.label_3.setText(_translate("Dialog", "Enable fetch of remotes: "))
        self.label_4.setText(_translate("Dialog", "Please also ensure you have configured a git difftool."))
        self.label.setText(_translate("Dialog", "Open IDE command:"))
        self.label_2.setText(_translate("Dialog", "Open terminal command: "))
        self.label_settings_location.setText(_translate("Dialog", "Application settings will be saved in\n"
"/home/abc/.config/gitscan/"))
