name: Test coverage

on: [push, workflow_dispatch]

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - run: echo "Triggered by a ${{ github.event_name }} and running branch ${{ github.ref }} on a ${{ runner.os }} server"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.txt
    - name: Check test coverage
      run: |
        target_coverage_pc=80
        coverage_pc=$(pytest --cov=gitscan/scanner tests | awk '$1 == "TOTAL" {print $NF+0}')
        exit $(( coverage_pc < target_coverage_pc ))
