name: Pycodestyle

on: [push, workflow_dispatch]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - run: echo "Triggered by a ${{ github.event_name }} and running branch ${{ github.ref }} on a ${{ runner.os }} server"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        pip install -r requirements.txt
    - name: Lint with pycodestyle
      run: |
        pycodestyle $(git ls-files '*.py') --exclude=*/gui/* --ignore=E501,W503
