name: Pyright

on: [push, workflow_dispatch]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - run: echo "Triggered by a ${{ github.event_name }} and running branch ${{ github.ref }} on a ${{ runner.os }} server"
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyright
        pip install -r requirements.txt
        pip install types-psutil
    - name: Type check with mypy
      run: |
        pyright .
